GET http://localhost:3000/tasks
###

GET http://localhost:3000/tasks/012-345

###
POST http://localhost:3000/tasks
content-type: application/json

{
    "title": "Cualquier cosa",
    "description": "Imprimir la tarea de la profe Liz",
    "priority": "Alta",
    "status": "Pendiente"
}

###

DELETE http://localhost:3000/tasks/6a4e82ba701b8143a6566eda

###

PATCH  http://localhost:3000/tasks/6a47bf46ccd82626c9ea1f4a
content-type: application/json

{
    "status": "Completada"
}